# Generated by Django 4.1.3 on 2022-12-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID телеграм чата')),
                ('nickname', models.TextField(verbose_name='Никнейм')),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('state', models.IntegerField(choices=[(0, 'REGISTRATION'), (1, 'MAIN_MENU'), (2, 'RECORDING')], default=0, verbose_name='Текущее состояние')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
    ]
