# Generated by Django 4.1.4 on 2022-12-17 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID телеграм чата')),
                ('nickname', models.TextField(verbose_name='Никнейм')),
                ('full_name', models.TextField(verbose_name='ФИО')),
                ('state', models.IntegerField(choices=[(0, 'REGISTRATION'), (1, 'MAIN_MENU'), (2, 'RECORDING'), (3, 'CONFIRMATION')], default=0, verbose_name='Текущее состояние')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='ItemsForConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forrest_app.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('zavod', models.IntegerField()),
                ('year', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forrest_app.botuser')),
            ],
        ),
    ]
