# Generated by Django 4.1.4 on 2022-12-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forrest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='state',
            field=models.IntegerField(choices=[(0, 'REGISTRATION'), (1, 'MAIN_MENU'), (2, 'RECORDING'), (3, 'CONFIRMATION')], default=0, verbose_name='Текущее состояние'),
        ),
        migrations.CreateModel(
            name='ItemsForConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forrest_app.botuser')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('zavod', models.IntegerField()),
                ('year', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forrest_app.botuser')),
            ],
        ),
    ]
