# Generated by Django 4.1.3 on 2022-12-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forrest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(related_name='groups', to='forrest_app.adminbotuser'),
        ),
    ]
