# Generated by Django 4.1.3 on 2022-12-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forrest_app', '0002_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsForConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forrest_app.botuser')),
            ],
        ),
    ]
