# Generated by Django 4.1.3 on 2022-12-04 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forrest_app', '0002_alter_group_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Номер пары')),
                ('start', models.TextField(verbose_name='Начало')),
                ('end', models.TextField(verbose_name='Конец')),
            ],
            options={
                'verbose_name': 'Время пар',
                'verbose_name_plural': 'Время пар',
            },
        ),
        migrations.AlterModelOptions(
            name='adminbotuser',
            options={'verbose_name': 'Админ бота', 'verbose_name_plural': 'Админы бота'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Домашнее задание', 'verbose_name_plural': 'Домашние задания'},
        ),
        migrations.AlterModelOptions(
            name='homeworktype',
            options={'verbose_name': 'Тип домашнего задания', 'verbose_name_plural': 'Типы домашнего задания'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AlterField(
            model_name='adminbotuser',
            name='full_name',
            field=models.TextField(default=2, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminbotuser',
            name='nickname',
            field=models.TextField(verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='adminbotuser',
            name='telegram_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID в телеграм'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='default_room',
            field=models.TextField(verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='full_name',
            field=models.TextField(verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='short_name',
            field=models.TextField(verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(related_name='groups', to='forrest_app.adminbotuser', verbose_name='Администраторы чата'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_chat_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID чата в ТГ'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='exp_date',
            field=models.TextField(verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Номер домашнего задания'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forrest_app.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forrest_app.homeworktype', verbose_name='Тип домашней работы'),
        ),
        migrations.AlterField(
            model_name='homeworktype',
            name='name',
            field=models.TextField(verbose_name='Тип домашней работы'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact',
            field=models.TextField(verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.TextField(verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='second_name',
            field=models.TextField(verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='discipline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forrest_app.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room',
            field=models.TextField(verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week_day',
            field=models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week_type',
            field=models.BooleanField(choices=[(True, 'Четная'), (False, 'Нечетная')], verbose_name='Четность недели'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forrest_app.timebot', verbose_name='Время'),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
