# Generated by Django 4.1.3 on 2022-12-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forrest_app', '0003_itemsforconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='state',
            field=models.IntegerField(choices=[(0, 'REGISTRATION'), (1, 'MAIN_MENU'), (2, 'RECORDING'), (3, 'CONFIRMATION')], default=0, verbose_name='Текущее состояние'),
        ),
    ]
