# Generated by Django 4.1.3 on 2022-12-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forrest_app', '0004_alter_teacher_options_homework_group_timetable_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forrest_app.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forrest_app.group', verbose_name='Группа'),
        ),
    ]
