name: PR linting

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Github-Linter
      uses: github/super-linter@v4.9.7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
