name: PR linting

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Github-Linter
      uses: github/super-linter@v3.15.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
