name: Lint

on:
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install mypy

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --docstring-min-length=20 --disable=C0114,C0115 --fail-under=8

    - name: Analysing the code with mypy
      run: |
        mypy $(git ls-files '*.py') --warn-unused-configs \
                            --disallow-any-generics --disallow-untyped-calls \
        --disallow-untyped-defs --disallow-incomplete-defs --check-untyped-defs --disallow-untyped-decorators \
        --no-implicit-optional --warn-redundant-casts --warn-unused-ignores --warn-return-any --no-implicit-reexport \
        --strict-equality --strict-concatenate
